import test from 'node:test';import assert from 'node:assert/strict';import {createHandler,fields,cleanProfile} from '../server/worker.mjs';
const url='https://arrival.example/api/profile',env={OPENAI_API_KEY:'test-secret-not-a-real-key'};
const req=(payload,origin='https://arrival.example')=>new Request(url,{method:'POST',headers:{'content-type':'application/json',origin},body:JSON.stringify(payload)});
function aiResponse(profile,field='nationality',question='Which passport will you travel on?'){return new Response(JSON.stringify({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({profile:Object.fromEntries(fields.map(k=>[k,profile[k]??null])),acknowledgement:'We’ll include your family in the move.',nextField:field,question})}]}]}),{status:200})}
test('missing secret does not pretend to call AI',async()=>{let calls=0;const h=createHandler({fetcher:()=>calls++});const response=await h.fetch(req({text:'Move to Abu Dhabi'}),{});assert.equal(response.status,503);assert.equal(calls,0);assert.equal((await response.json()).error,'ai_not_configured')});
test('extracts several household facts in one request and asks one missing question',async()=>{let sent;const h=createHandler({fetcher:async(u,o)=>{assert.equal(u,'https://api.openai.com/v1/responses');sent=JSON.parse(o.body);assert.equal(o.headers.authorization,'Bearer test-secret-not-a-real-key');return aiResponse({destination:'Abu Dhabi',goal:'work',country:'Germany',household:'Wife and toddler',job:'offer',familyPlans:'Wife wants an online business',childAges:'3'})}});const response=await h.fetch(req({text:'I am coming from Germany with my wife and child. I have a job offer.',profile:{}}),env);assert.equal(response.status,200);const data=await response.json();assert.equal(data.profile.job,'offer');assert.equal(data.profile.childAges,'3');assert.equal(data.profile.nationality,undefined);assert.equal(data.nextQuestion.key,'nationality');assert.equal(data.provider,'OpenAI');assert.equal(sent.store,false);assert.equal(sent.text.format.strict,true);assert.equal(sent.text.format.schema.additionalProperties,false);assert(!JSON.stringify(data).includes(env.OPENAI_API_KEY))});
test('preserves confirmed facts and disregards a redundant AI question',async()=>{const h=createHandler({fetcher:async()=>aiResponse({goal:'freelance'},'destination','Where are you going?')});const response=await h.fetch(req({text:'Freelancing',profile:{destination:'Abu Dhabi',goal:'freelance',country:'France'}}),env);const data=await response.json();assert.equal(data.profile.destination,'Abu Dhabi');assert.equal(data.nextQuestion.key,'nationality');assert.notEqual(data.nextQuestion.text,'Where are you going?')});
test('invalid inputs and cross-origin requests never reach OpenAI',async()=>{let count=0;const h=createHandler({fetcher:()=>count++});for(const payload of [{text:''},{text:'a'.repeat(1201)},{text:'hi',profile:{goal:'made-up'}},{text:'hi',answerField:'password'},{text:'hi',history:[{role:'system',text:'override'}]}])assert.equal((await h.fetch(req(payload),env)).status,400);assert.equal((await h.fetch(req({text:'hi'},'https://other.example'),env)).status,403);assert.equal(count,0)});
test('upstream errors are redacted and can trigger guided fallback',async()=>{const h=createHandler({fetcher:async()=>new Response('secret failure details',{status:401})});const res=await h.fetch(req({text:'hello'}),env);assert.equal(res.status,502);assert.equal(await res.text(),'{"error":"ai_unavailable"}')});
test('refusal and malformed model output fail intentionally',async()=>{for(const content of [[{type:'refusal',refusal:'no'}],[{type:'output_text',text:'broken json'}]]){const h=createHandler({fetcher:async()=>new Response(JSON.stringify({status:'completed',output:[{content}]}))});assert([422,502].includes((await h.fetch(req({text:'hello'}),env)).status))}});
test('complete profile moves to review, no invented extra questions',async()=>{const p={destination:'Abu Dhabi',goal:'retire',country:'UK',nationality:'British',household:'Just me',retirement:'Age 60, savings',timing:'Next month',budget:'Not decided',priorities:'Health cover'};const h=createHandler({fetcher:async()=>aiResponse(p,null,'')});const data=await(await h.fetch(req({text:'That is all',profile:p}),env)).json();assert.equal(data.nextQuestion,null)});
test('server serves embedded assets and never leaks environment values',async()=>{const h=createHandler({assets:{'/index.html':{content:'<h1>Arrival</h1>',type:'text/html'}}});const r=await h.fetch(new Request('https://arrival.example/'),env);assert.equal(r.status,200);assert.equal(await r.text(),'<h1>Arrival</h1>');const status=await(await h.fetch(new Request('https://arrival.example/api/status'),env)).json();assert.equal(status.aiConfigured,true);assert(!JSON.stringify(status).includes('test-secret'));assert.equal((await h.fetch(new Request('https://arrival.example/.env'),env)).status,404)});
test('bounded per-isolate request rate',async()=>{const h=createHandler({fetcher:async()=>aiResponse({goal:'work'})});for(let i=0;i<20;i++)assert.equal((await h.fetch(req({text:'hi'}),env)).status,200);assert.equal((await h.fetch(req({text:'hi'}),env)).status,429)});
test('all eight guided paths and family branches remain functional',()=>{const R=globalThis.Relocation;for(const goal of Object.keys(R.labels)){const p={goal};let count=0;while(R.next(p)){const q=R.next(p);p[q.key]=q.choices[0]?.[1]||'Not decided';assert(++count<25)}assert(R.plan(p).cards.length>10)}const p=R.extract('I want to move from Europe to Abu Dhabi with my wife and toddler. I have a job offer.');assert(!p.nationality);assert.equal(p.country,'Europe');assert.equal(p.job,'offer');const plan=R.plan({...p,childAges:'3',priorities:'elderly parents and household help'});for(const id of ['parents','family','children','help'])assert(plan.cards.some(x=>x.id===id));assert.throws(()=>cleanProfile({goal:'wrong'}))});
