const R=window.Relocation,$=s=>document.querySelector(s);
const STORAGE='arrival-conversation-v1';
let aiAvailable=false,busy=false;
let state={profile:{},messages:[],mode:'chat',started:false,edit:null,done:{}};
try{const saved=JSON.parse(localStorage.getItem(STORAGE));if(saved&&typeof saved.profile==='object'&&Array.isArray(saved.messages)&&['chat','review','plan'].includes(saved.mode)){state={...state,...saved};state.edit=null;state.messages=state.messages.filter(x=>['user','assistant'].includes(x.role)&&typeof x.text==='string').slice(-100);}}catch{}
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(state))}catch{}}
function add(role,text){state.messages.push({role,text});save()}
function current(){if(state.edit)return R.questions(state.profile).find(q=>q.key===state.edit);if(state.aiNext&&state.profile[state.aiNext.key]===undefined&&R.questions(state.profile).some(q=>q.key===state.aiNext.key))return state.aiNext;return R.next(state.profile)}
function ask(prefix=''){const q=current();if(!q){state.mode='review';save();render();return}add('assistant',(prefix?prefix+'\n\n':'')+q.text+(q.help?'\n'+q.help:''));render()}
function guidedSubmit(text,canonical){
state.aiNext=null;text=text.trim();if(!text)return;if(text.length>1200){$('#voice-status').textContent='Please keep the message under 1,200 characters.';return}
if(state.mode!=='chat')return;add('user',text);$('#answer').value='';
if(!state.started){state.started=true;state.profile=R.extract(text,state.profile);state.profile.context=text;let prefix=state.profile.destination&&state.profile.destination!=='Abu Dhabi'?`You mentioned ${state.profile.destination}. I’ll keep that in your profile. This demo gives you an Abu Dhabi starting point to explore alongside your original destination.`:'Let’s build a practical plan for Abu Dhabi.';ask(prefix);return}
const q=current();if(!q)return;const value=canonical??R.normalise(q,text);if(!value){ask('I couldn’t confidently identify that. Choose the closest option, or tell me a little more.');return}
if(q.key==='goal'&&!Object.hasOwn(R.labels,value)){ask('Choose the closest goal so I can tailor the next questions.');return}
state.profile[q.key]=value;state.profile=R.extract(text,state.profile);
if(q.key==='goal'){delete state.profile.job;delete state.profile.activity;delete state.profile.companyType;delete state.profile.jurisdiction;delete state.profile.trading;delete state.profile.retirement;delete state.profile.investment;}
if(q.key==='household'){delete state.profile.familyPlans;delete state.profile.childAges;}
if(state.edit){state.edit=null;if(!R.next(state.profile)){state.mode='review';save();render();return}}
let prefix='';if(q.key==='nationality'&&/europe|eu citizen|european/i.test(value))prefix='I’ll record that as a region for now. Check the exact passport nationality before confirming entry eligibility.';
if(q.key==='goal'&&value==='trade')prefix='We’ll separate trading your own funds from providing financial services.';
if(q.key==='household'&&/parent/i.test(value))prefix='We’ll include parent residence and age-appropriate health cover.';
ask(prefix);
}
function setBusy(value){busy=value;$('#send').disabled=value;$('#restart').disabled=value;$('#mic').disabled=value;$('#send').textContent=value?'Thinking…':'Send';$('#composer').setAttribute('aria-busy',String(value));document.querySelectorAll('[data-choice]').forEach(b=>b.disabled=value)}
async function submit(text,canonical){
text=text.trim();if(!text||busy||state.mode!=='chat'||(state.started&&!current()))return;
if(text.length>1200){$('#voice-status').textContent='Please keep the message under 1,200 characters.';return}
if(!aiAvailable){guidedSubmit(text,canonical);return}
const field=state.started?current()?.key:null;const edit=state.edit;
setBusy(true);$('#ai-feedback').textContent='Understanding your situation…';
try{
const response=await fetch('/api/profile',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text,profile:state.profile,answerField:field,history:state.messages.slice(-10)}),signal:AbortSignal.timeout(30000)});
if(!response.ok)throw Error('AI unavailable');const data=await response.json();if(!data.profile||data.provider!=='OpenAI')throw Error('Invalid AI response');
add('user',text);$('#answer').value='';state.started=true;state.profile={...data.profile,context:state.profile.context||text};state.aiNext=data.nextQuestion;state.edit=null;
state.mode=data.nextQuestion?'chat':'review';
const reply=[data.acknowledgement,data.nextQuestion?.text].filter(Boolean).join('\n\n');if(reply)add('assistant',reply);
$('#ai-feedback').textContent='Profile updated with OpenAI.';$('#ai-badge').textContent='OpenAI';save();render();
}catch{
// Explicit fallback keeps the working demo available without pretending a model answered.
$('#ai-feedback').textContent='AI is unavailable right now. Continuing with guided questions.';$('#ai-badge').textContent='Guided fallback';aiAvailable=false;state.edit=edit;guidedSubmit(text,canonical);
}finally{setBusy(false)}
}
async function checkAI(){try{const response=await fetch('/api/status',{cache:'no-store'});if(!response.ok)throw Error();const status=await response.json();aiAvailable=status.aiConfigured===true;$('#ai-badge').textContent=aiAvailable?'OpenAI enabled':'Guided demo';$('#ai-feedback').textContent=aiAvailable?'OpenAI helps understand your answers and build your profile.':'Guided mode · OpenAI is not connected yet.';}catch{$('#ai-badge').textContent='Guided demo';$('#ai-feedback').textContent='Guided mode · OpenAI is not connected yet.'}}
function profileHTML(editable=false){return `<div class="profile-list">${Object.entries(state.profile).filter(([k])=>!['context'].includes(k)).map(([k,v])=>`<div class="profile-item"><span>${escape(R.fieldLabel(k))}</span><strong>${escape(R.valueLabel(k,v))}</strong>${editable?`<button data-edit="${escape(k)}">Change ${escape(R.fieldLabel(k).toLowerCase())}</button>`:''}</div>`).join('')}</div>`}
function render(){const chat=state.mode==='chat';$('#conversation').hidden=!chat;$('#review').hidden=state.mode!=='review';$('#result').hidden=state.mode!=='plan';$('#profile-peek').hidden=state.mode!=='chat'||!Object.keys(state.profile).length;
$('#profile-details').innerHTML=profileHTML();
$('#profile-peek').open=state.started&&state.mode==='chat';
if(chat){$('.heading').hidden=state.started;$('#messages').innerHTML=state.messages.map(m=>`<div class="message ${m.role}"><span class="speaker">${m.role==='assistant'?'ARRIVAL':'YOU'}</span>${escape(m.text)}</div>`).join('');const q=current();const choices=!state.started?[['I’m moving with my family','I want to move to Abu Dhabi with my family.'],['I work as a freelancer','I am a freelancer moving to Abu Dhabi.'],['I want to open a company','I want to open a company in Abu Dhabi.']]:q?.choices||[];
$('#suggestions').innerHTML=choices.map(([l,v])=>`<button type="button" data-choice="${escape(v)}">${escape(l)}</button>`).join('');document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>submit(state.started?b.textContent:b.dataset.choice,state.started?b.dataset.choice:undefined));if(state.started&&!q){$('#suggestions').innerHTML='<button id="return-review">Review my profile</button>';$('#return-review').onclick=()=>{state.mode='review';render()};}$('#answer').placeholder=!state.started?'I want to move to Abu Dhabi…':'Type your answer…';}
if(state.mode==='review'){$('#review').innerHTML=`<span class="eyebrow">YOUR MOVE, YOUR CIRCUMSTANCES</span><h2>Does this look right?</h2><p>Review the details before we build your plan. You can change any answer.</p><div class="card">${profileHTML(true)}</div><div class="actions"><button id="generate" class="primary">Build my relocation plan</button><button id="continue-chat" class="secondary">Review the conversation</button></div>`;document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{state.edit=b.dataset.edit;state.mode='chat';ask('Let’s update that detail.');$('#answer').focus()});$('#generate').onclick=()=>{state.mode='plan';save();syncPlanner();render();window.scrollTo({top:0,behavior:'smooth'})};$('#continue-chat').onclick=()=>{state.mode='chat';render();$('#suggestions').innerHTML='<button id="return-review">Back to profile review</button>';$('#return-review').onclick=()=>{state.mode='review';render()};$('#composer').hidden=true;};}
$('#composer').hidden=chat&&state.started&&!current();
if(state.mode==='plan')renderPlan();save();
if(chat&&state.started&&current()){requestAnimationFrame(()=>$('#composer').scrollIntoView({behavior:'smooth',block:'nearest'}))}
}
function renderPlan(){const result=R.plan(state.profile),groups=['Before you arrive','Your first days','Get settled','Feel at home'];const done=result.cards.filter(x=>state.done[x.id]).length;$('#result').innerHTML=`<div class="result-heading"><div><span class="eyebrow">A PLAN BUILT AROUND YOU</span><h2>Your Abu Dhabi starting point</h2><p>${escape(R.labels[state.profile.goal]||'Explore your options')} · ${escape(state.profile.timing||'Timing to confirm')}</p></div><button id="print-plan" class="secondary">Print plan</button></div>${state.profile.destination!=='Abu Dhabi'?`<div class="notice">You mentioned ${escape(state.profile.destination)}. This demo specialises in Abu Dhabi; local services below are an Abu Dhabi alternative, not a complete plan for your original destination.</div>`:''}<div class="route"><span class="eyebrow">YOUR FIRST DECISION</span><p>${escape(result.route)}</p></div><details class="card"><summary>View your profile</summary>${profileHTML()}</details><div class="progress" role="status">${done} of ${result.cards.length} actions checked off</div>${groups.map(g=>`<h3 class="phase">${g.toUpperCase()}</h3>${result.cards.filter(x=>x.phase===g).map(x=>`<article class="task ${state.done[x.id]?'completed':''}"><div class="task-title"><input id="task-${x.id}" type="checkbox" data-task="${x.id}" ${state.done[x.id]?'checked':''}><label for="task-${x.id}">${escape(x.title)}</label></div><p>${escape(x.body)}</p><div class="task-links">${x.links.map(([l,u])=>`<a href="${escape(u)}" ${u.startsWith('https:')?'target="_blank" rel="noopener"':''}>${escape(l)}</a>`).join('')}</div></article>`).join('')}`).join('')}<div class="notice">This is a planning shortlist based on your answers. It does not confirm visa eligibility, permission to work, bank approval or investment suitability. Costs and timings must be confirmed with each provider.</div><div class="actions"><button id="revise" class="primary">Edit my profile</button><a href="planner.html" class="secondary">Open full checklist & budget</a></div>`;document.querySelectorAll('[data-task]').forEach(b=>b.onchange=()=>{state.done[b.dataset.task]=b.checked;save();const article=b.closest('article');article.classList.toggle('completed',b.checked);$('.progress').textContent=`${result.cards.filter(x=>state.done[x.id]).length} of ${result.cards.length} actions checked off`});$('#revise').onclick=()=>{state.mode='review';render();window.scrollTo({top:0,behavior:'smooth'})};$('#print-plan').onclick=()=>window.print()}
function syncPlanner(){try{let old=JSON.parse(localStorage.getItem('arrival-demo-v1'))||{};const business=state.profile.goal==='business';old.journey=business?'company':'person';old.purpose=business?(['new','branch','representative'].includes(state.profile.companyType)?state.profile.companyType:'new'):state.profile.goal==='freelance'||['retire','invest','trade'].includes(state.profile.goal)?'self':state.profile.job==='search'?'search':/family|partner|wife|child/i.test(state.profile.household||'')?'family':'offer';old.jurisdiction=state.profile.jurisdiction||'undecided';old.stage=0;old.view='plan';localStorage.setItem('arrival-demo-v1',JSON.stringify(old));}catch{}}
$('#composer').onsubmit=e=>{e.preventDefault();submit($('#answer').value)};$('#answer').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();submit($('#answer').value)}};
$('#restart').onclick=()=>{if(state.started&&!window.confirm('Start a fresh conversation? This clears this conversation and its plan checkmarks.'))return;if(listening)recognition?.stop();state={profile:{},messages:[],mode:'chat',started:false,edit:null,done:{}};$('#answer').value='';save();add('assistant','Hi, I’m Arrival. Tell me what brings you to the UAE, and I’ll help you explore a move to Abu Dhabi.');render();window.scrollTo({top:0,behavior:'smooth'});$('#answer').focus()};
let recognition=null,listening=false;const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
if(SpeechRecognition){recognition=new SpeechRecognition();recognition.lang='en-US';recognition.continuous=false;recognition.interimResults=false;recognition.onstart=()=>{listening=true;$('#mic').setAttribute('aria-pressed','true');$('#mic-label').textContent='Stop';$('#voice-status').textContent='Listening… Speak your answer. It will appear below for you to review.'};recognition.onresult=e=>{const transcript=Array.from(e.results).map(r=>r[0].transcript).join(' ');$('#answer').value=($('#answer').value+' '+transcript).trim().slice(0,1200);$('#voice-status').textContent='Your words are ready. Review them, then press Send.';$('#answer').focus()};recognition.onerror=e=>{$('#voice-status').textContent=e.error==='not-allowed'?'Microphone access was not allowed. You can type your answer instead.':e.error==='no-speech'?'No speech was detected. Try again or type your answer.':'Voice input is unavailable right now. Please type your answer.'};recognition.onend=()=>{listening=false;$('#mic').setAttribute('aria-pressed','false');$('#mic-label').textContent='Speak'};
$('#mic').onclick=()=>{if(listening){recognition.stop();return;}$('#voice-status').textContent='Your browser may process speech using its speech service. Allow microphone access to continue.';try{recognition.start()}catch{$('#voice-status').textContent='Could not start voice input. Type your answer or try again.'}};
}else{$('#voice-status').textContent='Voice input is not supported in this browser. Typing works normally.';$('#mic').onclick=()=>{$('#voice-status').textContent='This browser does not support voice input. Please type your answer.';$('#answer').focus()};}
if(!state.messages.length)add('assistant','Hi, I’m Arrival. Tell me what brings you to the UAE, and I’ll help you explore a move to Abu Dhabi.');
render();
checkAI();
// Feature-detected WebMCP uses the same visible flow and validation.
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_relocation_profile',description:'Read the current relocation profile and the next guided question.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({profile:state.profile,mode:state.mode,nextQuestion:current()?.text||null})})).catch(()=>{});Promise.resolve(document.modelContext.registerTool({name:'answer_relocation_question',description:'Submit a message to the guided relocation conversation; does not apply for visas or make bookings.',inputSchema:{type:'object',properties:{text:{type:'string',minLength:1,maxLength:1200}},required:['text'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(typeof input?.text!=='string'||!input.text.trim()||input.text.length>1200||state.mode!=='chat'||(state.started&&!current()))throw Error('A valid answer and an active conversation are required.');return submit(input.text).then(()=>({profile:state.profile,mode:state.mode,nextQuestion:current()?.text||null}));}})).catch(()=>{});}catch{}}
