/* Guided demo logic. No eligibility decisions, live quotations or language-model calls. */
(function(root){
const labels={work:'Live & work',family:'Explore with my family',freelance:'Freelance / create',business:'Open a company / branch',retire:'Retire',invest:'Live & invest',trade:'Trade / invest in markets',explore:'Explore my options'};
const sources={entry:'https://u.ae/en/information-and-services/visa-and-emirates-id/Visa-information/do-you-need-an-entry-permit-or-a-visa-to-enter-the-uae',work:'https://u.ae/en/information-and-services/jobs/employment-in-the-private-sector/preparing-to-work',residence:'https://u.ae/en/information-and-services/visa-and-emirates-id/Visa-information/general-provisions-for-the-residence-visa',family:'https://u.ae/en/information-and-services/visa-and-emirates-id/residence-visas/residence-visa-for-family-members',green:'https://www.added.gov.ae/en/live/long-term-residency/abu-dhabi-green-visa/for-freelancers',golden:'https://icp.gov.ae/en/services/uae-golden-residency/',retire:'https://u.ae/en/information-and-services/visa-and-emirates-id/residence-visas/residence-visa-for-the-retired',icp:'https://icp.gov.ae/',tamm:'https://www.tamm.abudhabi/',business:'https://www.added.gov.ae/en/set-up/establish-your-business',zones:'https://www.added.gov.ae/en/grow/competitive-landscape/mainland-and-freezones',tax:'https://tax.gov.ae/',hafilat:'https://admobility.gov.ae/en/Hafilat',taxi:'https://admobility.gov.ae/en/taxi-booking',adgm:'https://www.adgm.com/',familyoffice:'https://www.adgm.com/business-areas/family-offices',health:'https://www.doh.gov.ae/',mohre:'https://www.mohre.gov.ae/',housing:'https://mservices.dma.abudhabi.ae/mservices/account/login?l=en',residents:'https://www.adro.gov.ae/',mofa:'https://www.mofa.gov.ae/'};
const question=(key,text,choices=[],help='')=>({key,text,choices,help});
function questions(p){let a=[question('destination','Where in the UAE are you thinking of moving?',[['Abu Dhabi','Abu Dhabi'],['Dubai','Dubai'],['Still deciding','Still deciding']]),question('goal','What would you like your move to make possible?',Object.entries(labels).map(([v,l])=>[l,v])),question('country','Where are you living right now?',[], 'A country or region is enough.'),question('nationality','Which passport nationality will you travel on?',[], 'Entry rules depend on your passport, not just where you live. You can say “prefer not to share”.'),question('household','Who would be coming with you?',[['Just me','Just me'],['My partner','My partner'],['Partner & children','Partner & children'],['Including my parents','Including my parents']])];
const family=/family|partner|wife|husband|child|kid|toddler|parent|spouse/i.test(p.household||'');
if(family)a.push(question('familyPlans','What would the other adults like to do after the move?',[], 'For example: my partner will work online, and my parents will retire.'));
if(family&&/child|kid|toddler|kindergarten|school|family of [3-9]|family of three/i.test((p.household||'')+' '+(p.context||'')))a.push(question('childAges','How old are the children?',[], 'This helps us put nursery and school planning in the right place.'));
if(p.goal==='work'||p.goal==='family')a.push(question('job','Do you already have a job lined up?',[['Yes, I have an offer','offer'],['I will look for work','search'],['Not sure yet','explore']]));
if(p.goal==='work'||p.goal==='family'||p.goal==='freelance')a.push(question('activity','What kind of work do you do?',[], 'For example: software engineering, consulting, design or content creation.'));
if(p.goal==='business')a.push(question('companyType','How would you like to set up the business?',[['A new company','new'],['A branch of my company','branch'],['A representative office','representative'],['Still deciding','undecided']]),question('activity','What will the business actually do?',[], 'The activity helps determine licensing and permissions.'),question('jurisdiction','Have you chosen a licensing route?',[['Abu Dhabi mainland','mainland'],['A free zone','freezone'],['Help me compare','undecided']]));
if(p.goal==='trade')a.push(question('trading','Will you trade your own money, or provide services to others?',[['Only my own money','own'],['Manage money / advise others','services'],['Work for a trading firm','employee'],['Still deciding','undecided']]));
if(p.goal==='retire')a.push(question('retirement','Tell me a little about your retirement plans.',[], 'Your age and whether you expect to use savings, income or property for the move. Broad details are enough.'));
if(p.goal==='invest')a.push(question('investment','What would you like to invest in or set up?',[['Property & a home','Property & a home'],['A business','A business'],['A family office','A family office'],['Explore the options','Explore the options']]));
a.push(question('timing','When would you like to make the move?',[['Within a month','Within a month'],['In 1–3 months','In 1–3 months'],['Later this year','Later this year'],['Just exploring','Just exploring']]),question('budget','What monthly living budget feels comfortable for you?',[], 'An approximate amount in AED is useful, or say “not decided”. Setup and investment costs are separate.'),question('priorities','What else should your plan take care of?',[], 'For example: health cover, elderly parents, property, a Golden Visa, moving wealth, a will or household help. “Nothing else” is fine.'));
return a;}
function next(p){return questions(p).find(q=>p[q.key]===undefined)}
function classify(text){const s=text.toLowerCase();if(/family office|open.*(?:company|branch|office)|set.?up.*(?:company|business)|launch.*business|start.*(?:business|company)/.test(s))return 'business';if(/retir/.test(s))return 'retire';if(/crypto|forex|stock trad|trading|trader/.test(s))return 'trade';if(/freelanc|consultant|influenc|creator|self.employ/.test(s))return 'freelance';if(/high.net.worth|wealth|invest|golden visa/.test(s))return 'invest';if(/job|work|employ/.test(s))return 'work';if(/family|wife|husband|partner|children|toddler/.test(s))return 'family';if(/explor|options/.test(s))return 'explore';}
function extract(text,p={}){const s=text.toLowerCase(),out={...p};const destinations=[['abu dhabi','Abu Dhabi'],['abudhabi','Abu Dhabi'],['dubai','Dubai'],['sharjah','Sharjah'],['ajman','Ajman'],['ras al khaimah','Ras Al Khaimah'],['rak','Ras Al Khaimah'],['fujairah','Fujairah'],['umm al quwain','Umm Al Quwain']];const dest=destinations.find(([term])=>new RegExp('\\b'+term+'\\b').test(s));if(dest&&!out.destination)out.destination=dest[1];const g=classify(text);if(g&&!out.goal)out.goal=g;const location=text.match(/(?:living in|live in|moving from|coming from|from) (Europe|UK|United Kingdom|France|Germany|Italy|Spain|Netherlands|India|Pakistan|USA|United States|Canada|Australia|South Africa)\b/i);if(location&&!out.country)out.country=location[1];const passport=text.match(/(?:my passport is|passport nationality is|I have a|I hold a) ([A-Za-z ]{2,35}?) passport/i);if(passport&&!out.nationality)out.nationality=passport[1];if(!out.household){if(/(?:with |bringing |bring |and my ).*(?:family|wife|husband|partner|children|parents)|family of/.test(s))out.household=text;else if(/alone|just me|by myself/.test(s))out.household='Just me';}if(!out.job&&/job offer|have an offer|have a job|got a job|husband.*(?:has|got).*job/i.test(text))out.job='offer';if(!out.companyType&&/branch/.test(s))out.companyType='branch';return out;}
function normalise(q,text){const exact=q.choices.find(([l,v])=>text.toLowerCase()===l.toLowerCase()||text.toLowerCase()===v.toLowerCase());if(exact)return exact[1];if(q.key==='goal')return classify(text);if(q.key==='job'){if(/offer|lined up|already.*job|^yes/i.test(text))return 'offer';if(/search|hunt|look|^no|find.*job/i.test(text))return 'search';return 'explore'}if(q.key==='companyType'){if(/branch/i.test(text))return 'branch';if(/representative/i.test(text))return 'representative';if(/new|start/i.test(text))return 'new';return 'undecided'}if(q.key==='jurisdiction'){if(/mainland/i.test(text))return 'mainland';if(/free.?zone|adgm|masdar|kezad|twofour/i.test(text))return 'freezone';return 'undecided'}if(q.key==='trading'){if(/own|personal|my money/i.test(text))return 'own';if(/others|client|manag|advis|service/i.test(text))return 'services';if(/firm|employ/i.test(text))return 'employee';return 'undecided'}return text;}
function fieldLabel(key){return ({destination:'Destination mentioned',goal:'Main goal',country:'Current location',nationality:'Passport nationality',household:'Moving with',familyPlans:'Other adults’ plans',childAges:'Children’s ages',job:'Job situation',activity:'Work / business activity',companyType:'Company structure',jurisdiction:'Licensing route',trading:'Trading activity',retirement:'Retirement plans',investment:'Investment interests',timing:'Target timing',budget:'Monthly living budget',priorities:'Other priorities'})[key]||key}
function valueLabel(key,value){const q=questions({goal:key==='companyType'||key==='jurisdiction'?'business':key==='trading'?'trade':key==='investment'?'invest':'work'}).find(x=>x.key===key);return q?.choices.find(x=>x[1]===value)?.[0]||value}
function plan(p){const cards=[],add=(id,phase,title,body,links)=>cards.push({id,phase,title,body,links});const all=Object.values(p).join(' '),family=/partner|family|wife|husband|child|kid|parent|spouse/i.test(p.household||'');
let route='Start by comparing residence routes with ICP, based on your purpose, passport and sponsor arrangements.';
if(p.goal==='work'||p.goal==='family')route=p.job==='offer'?'Start with your employer: confirm work authorisation, residence sponsorship, fees and family support in writing.':'Explore lawful entry and job-search options first. Secure appropriate work authorisation before starting a job.';
if(p.goal==='freelance')route='Compare an activity-specific freelance licence or permit with the residence route. Green Residence is worth checking, but an economic licence alone does not establish eligibility.';
if(p.goal==='business')route='Choose the legal structure and licensing authority for your activity before committing to premises. Business licensing and personal residence are separate steps.';
if(p.goal==='retire')route='Explore the retirement residence route with ICP. Age, work history and financial evidence matter; your plan is a starting point, not an approval.';
if(p.goal==='invest')route='Compare investor or other residence options, including relevant Golden Residency categories. Wealth alone does not establish eligibility.';
if(p.goal==='trade')route=p.trading==='own'?'Build a personal residence and banking plan for trading your own funds. Confirm tax treatment for your circumstances; do not assume every trading activity is exempt.':'Clarify the activity with the appropriate financial regulator and licensing authority. A residence visa does not authorise managing funds or providing financial services.';
add('entry','Before you arrive','Confirm your entry route','Check the entry requirements for your passport nationality and travel purpose with the official portal and airline. Your current country of residence alone does not establish visa eligibility. Confirm passport validity and any required permit before booking.',[['UAE entry guidance',sources.entry],['ICP',sources.icp]]);
if(p.goal==='work'||(p.goal==='family'&&p.job!=='explore'))add('work','Before you arrive',p.job==='offer'?'Ask your employer for a relocation checklist':'Start your job search before travelling',p.job==='offer'?'Confirm the offer, work permit process, residence arrangements and which costs the employer covers. Ask about insurance for yourself and dependants.':'Prepare a targeted CV and use employer career pages, LinkedIn, Bayt and GulfTalent. Contact recruiters relevant to your industry and request an online meeting or an appointment; interviews and placements are not guaranteed. Verify offers before paying any intermediary.',p.job==='offer'?[['Employment guidance',sources.work]]:[['LinkedIn','https://www.linkedin.com/jobs/'],['Bayt','https://www.bayt.com/'],['GulfTalent','https://www.gulftalent.com/'],['Hays UAE','https://www.hays.ae/'],['Michael Page UAE','https://www.michaelpage.ae/']]);
if(p.goal==='freelance')add('freelance','Before you arrive','Compare freelance permission and Green Residence','Confirm which licence or work permit authorises your activity and clients. The freelance Green Residence category requires a MOHRE freelance permit, qualifying education and income evidence or financial solvency. Ask the authorities how your selected licensing route fits those requirements.',[['Official Green Residence criteria',sources.green],['TAMM',sources.tamm],['MOHRE',sources.mohre]]);
if(p.goal==='business'||/online business|family office|open.*office/i.test(all))add('business','Before you arrive','Choose your business setup route','Define the exact activity, legal structure, staffing and target customers. Compare mainland and relevant free zones. Request a route-specific checklist for trade name, formation, permissions, premises, establishment records and renewal fees. A branch or representative office needs its own parent-company document review.',[['ADDED setup',sources.business],['Compare jurisdictions',sources.zones],['TAMM',sources.tamm]]);
if(p.goal==='trade')add('trading','Before you arrive','Clarify trading and financial permissions',p.trading==='own'?'Tell banks and brokers the nature of your personal trading and prepare source-of-funds records. Confirm account eligibility, asset coverage and tax treatment directly. This plan does not recommend investments or platforms.':'If you advise clients, manage funds or operate a financial-services company, confirm the relevant regulator, licence and approved scope before operating. An employee must also confirm their work authorisation.',[['ADGM',sources.adgm],['Federal Tax Authority',sources.tax]]);
if(p.goal==='retire')add('retirement','Before you arrive','Check retirement eligibility and healthcare','Review the official age, work-history and financial criteria. Confirm the Abu Dhabi application route and evidence with ICP. Compare health insurance at your age, including pre-existing conditions and hospital access, before committing to the move.',[['Retirement residence guidance',sources.retire],['ICP',sources.icp]]);
if(p.goal==='invest'||/golden|property|high.net.worth|invest/i.test(all))add('golden','Before you arrive','Review investment and Golden Residency options','Choose the relevant category and confirm every evidence requirement. For property, verify the title, financing conditions and whether the proposed investment qualifies before purchase. Do not assume the investment or this profile guarantees a Golden Visa.',[['ICP Golden Residency',sources.golden],['Abu Dhabi services',sources.tamm]]);
add('documents','Before you arrive','Prepare the documents your route needs','Request the authority’s current checklist for passports, photos, qualifications, company papers or family certificates. Confirm attestation and translation requirements for each document; not every foreign-issued document follows the same process.',[['MOFA attestation services',sources.mofa],['ICP',sources.icp]]);
add('flight','Before you arrive','Arrange your flight and airport transfer','Include Etihad when comparing flights to Abu Dhabi. Check entry requirements, baggage, flexible fares and cancellation terms. Keep your temporary accommodation address and arrival documents handy; arrange a licensed airport transfer.',[['Etihad','https://www.etihad.com/'],['Abu Dhabi Taxi',sources.taxi]]);
add('stay','Before you arrive','Start with a flexible temporary home','Compare hotel apartments, serviced apartments and suitable holiday-home listings before signing a long lease. Check total cost, cancellation, kitchen/laundry facilities, listing permissions and the commute. For a family, check room capacity and nearby everyday services.',[['Booking.com','https://www.booking.com/'],['Airbnb','https://www.airbnb.com/'],['Living in Abu Dhabi',sources.residents]]);
add('medical','Your first days','Coordinate residence, medical and Emirates ID','Follow your sponsor or authority’s sequence. Residence applicants aged 18 and over generally need medical fitness screening. Use an approved centre, complete required Emirates ID application/biometrics and track residence processing. Timelines depend on the route and appointments.',[['Residence requirements',sources.residence],['ICP',sources.icp],['TAMM',sources.tamm]]);
add('health','Your first days',family?'Arrange health cover for each family member':'Arrange your health insurance','Check Abu Dhabi health insurance requirements and who must arrange and pay for coverage. Compare networks, exclusions, waiting periods and pre-existing-condition cover. Residence medical screening is separate from insurance; include dependants and elderly parents in the insurance discussion.',[['Department of Health Abu Dhabi',sources.health],['Abu Dhabi Residents Office',sources.residents]]);
add('identity','Your first days','Connect your phone and government services','Arrange a SIM with a licensed provider, checking the identification requirements. Set up UAE PASS where eligible and use TAMM and ICP for the services relevant to your route. Some services require their own apps even though this planner works in the browser.',[['TAMM',sources.tamm],['ICP',sources.icp],['e& UAE','https://www.etisalat.ae/'],['du','https://www.du.ae/']]);
add('transport','Your first days','Get around with taxis and Hafilat buses','Use Abu Dhabi Taxi and check live availability and fares with ride providers. Abu Dhabi public buses use Hafilat cards; consult Abu Dhabi Mobility for card and route details. Compare your likely commute before deciding on a car.',[['Abu Dhabi Taxi',sources.taxi],['Hafilat',sources.hafilat],['Uber Abu Dhabi','https://www.uber.com/global/en/r/cities/abu-dhabi-abu-dhabi-ae/'],['Careem','https://www.careem.com/'],['Yango','https://yango.com/']]);
if(family)add('family','Your first days','Plan each family member’s residence and work','Check dependent sponsorship eligibility and document requirements separately. If your partner will work online or start a business, confirm the necessary authorisation rather than assuming dependent residence covers it. Each person may need their own tailored route.',[['Family residence guidance',sources.family],['Working in the UAE',sources.work],['Business setup',sources.business]]);
if(/parent|elder/i.test(all))add('parents','Before you arrive','Check your parents’ residence and care needs','Ask ICP about the applicable parent sponsorship route, income/accommodation evidence and supporting documents. Compare age-specific insurance and care needs before travel. Do not assume parents have the same rules as a spouse or child.',[['Family sponsorship guidance',sources.family],['ICP',sources.icp],['Health authority',sources.health]]);
add('bank','Get settled','Prepare for personal and business banking','Ask the selected bank for its current account requirements, identity/residence evidence and any income or address records. Business accounts need a separate corporate and beneficial-owner file. Approval, minimum balances and timelines depend on the bank.',[['FAB','https://www.bankfab.com/'],['ADCB','https://www.adcb.com/'],['Wio','https://wio.io/']]);
if(p.goal==='invest'||/wealth|funds|capital|family office/i.test(all))add('wealth','Before you arrive','Plan wealth transfers and estate arrangements','Discuss account opening, transfer limits and source-of-funds evidence with the receiving bank before moving funds. Obtain advice on your previous country’s tax residence, UAE obligations and succession planning. For wills or a family office, use qualified legal and tax advisers and confirm the applicable framework.',[['ADGM family offices',sources.familyoffice],['Federal Tax Authority',sources.tax]]);
if(p.goal==='business'||p.goal==='freelance'||p.goal==='trade'||p.goal==='invest'||/business/i.test(all))add('tax','Get settled','Check business, tax and recordkeeping obligations','Review corporate tax, VAT and filing obligations for the actual activity and entity. Free-zone treatment is conditional. Separate personal investment from business activity, and ask an adviser about cross-border tax residence. Keep sourced records rather than relying on a blanket “tax-free” claim.',[['Federal Tax Authority',sources.tax]]);
add('home','Get settled','Decide where to live after exploring','Compare areas such as Al Reem, Yas, Saadiyat and Al Raha against your commute, household needs and budget. Inspect homes, verify agents and review payment terms. For a long-term lease, confirm Tawtheeq registration and utility requirements; for a purchase, obtain legal and financial due diligence.',[['Tenancy services',sources.housing],['Property Finder','https://www.propertyfinder.ae/'],['Abu Dhabi Residents Office',sources.residents]]);
if(p.childAges)add('children','Get settled','Explore nursery or school options','Use the children’s ages to decide whether nursery, kindergarten or school planning is relevant. Check admission ages, places, fees, documents, term dates and transport with schools and the Abu Dhabi education authority before committing.',[['ADEK','https://www.adek.gov.ae/']]);
if(/domestic|household help|servant|nanny|maid/i.test(all))add('help','Get settled','Hire household support through authorised channels','Use a licensed domestic-worker recruitment route. Confirm the contract, sponsorship, insurance, wages and employer obligations through MOHRE before hiring.',[['MOHRE',sources.mohre]]);
add('daily','Feel at home','Set up everyday services and local connections','Check food and shopping delivery coverage at your address. Browse professional and community events, arrange introductions and find a regular activity. Confirm organisers’ current dates and registration requirements.',[['Talabat','https://www.talabat.com/uae/city/abu-dhabi'],['noon Food','https://food.noon.com/'],['noon','https://www.noon.com/uae-en/'],['Hub71 events','https://www.hub71.com/index.php/events'],['Visit Abu Dhabi','https://visitabudhabi.ae/']]);
add('renewals','Feel at home','Track costs, renewals and next steps','Use the budget worksheet to enter confirmed quotes for travel, temporary housing, permits, insurance, deposits and living costs. Note which costs the employer covers. Add residence, ID, policy, licence and lease expiry dates to your calendar; residence is renewable, not a promise of permanent status.',[['Open checklist & budget','planner.html']]);
return {route,cards};}
root.Relocation={labels,sources,questions,next,extract,normalise,fieldLabel,valueLabel,plan};
})(typeof window!=='undefined'?window:globalThis);
